r"""The Teams side of streaming. READ THE FIRST SECTION BEFORE EDITING.

================================================================================
  TEAMS STREAMED UPDATES ARE CUMULATIVE. THEY ARE NOT DELTAS.
================================================================================

Every content update you send must contain ALL the text you have streamed so
far, not just the newest chunk. Microsoft's own words, from
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/streaming-ux :

    "While streaming, the agent messages must contain the previous streamed
    content. For example: This is an example of acceptable streaming
    response.  'A brown.'  'A brown fox.'  'A brown fox jumps over the
    fence.'  Non-example: This is an example of a streaming response that
    will return an error.  'A brown.'  'Hello.'"

    "For every response streaming update, the message content should be the
    latest version of the final message. This means that your agent should
    incorporate any new tokens generated by the LLMs. Append these tokens to
    the previous message version and then send it to the user."

If you send only the newest chunk, the user does not see text being appended.
They see the whole message bubble REPLACED by a fragment, and Teams may
reject the update outright. This is the single most common way to get Teams
streaming wrong, it looks fine in a unit test that only checks the last
update, and it is why ``test_renderer.py`` asserts the cumulative invariant
on EVERY emitted update rather than just the final one.

The direct consequence: the renderer must BUFFER the entire response in
middle-tier memory for the duration of the turn. ADR 005 accepted that cost
explicitly ("Buffering cumulative text for Teams means holding partial
responses in middle tier memory for the duration of a turn"). It is not an
oversight and it is not optimisable away.

--------------------------------------------------------------------------
THE PROTOCOL, AS DOCUMENTED
--------------------------------------------------------------------------
Source for everything in this section:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/streaming-ux

Three kinds of activity, in this order:

1. INFORMATIVE UPDATE - ``type: "typing"``, ``streamType: "informative"``.
   Tells the user what the agent is DOING ("Querying BigQuery..."). Rendered
   in the message bubble; the text stays visible until the next informative
   update or until the first content chunk replaces it. Informative text is
   capped at 1 KB / 1000 characters. These are NOT cumulative - each one
   replaces the last - because they are status, not content.

2. STREAMING CONTENT UPDATE - ``type: "typing"``, ``streamType: "streaming"``
   (the default). Carries the cumulative message text. After the first
   content update, informative updates no longer display.

3. FINAL MESSAGE - ``type: "message"``, ``streamType: "final"``. Ends the
   stream and leaves a normal, persisted Teams message. ``streamSequence``
   MUST NOT be set on this one.

Per-activity fields, carried in an entity of ``type: "streaminfo"``:

    "entities": [{
        "type": "streaminfo",
        "streamId": "<from the response to the FIRST activity>",
        "streamType": "informative" | "streaming" | "final",
        "streamSequence": <int, starts at 1, +1 per request, omitted on final>
    }]

Other rules that bite:

* The FIRST activity of a stream MUST include ``text``. Omit it and Teams
  answers ``400 BadRequest: Start streaming activities should include text``.
  That is why :meth:`ConnectorTeamsSink.content` will open a stream with an
  informative update if nobody opened one already.
* ``streamId`` comes back in the response to the first activity. Every
  subsequent activity must carry it.
* THROTTLE: "The throttling limit is 1 request per second." Exceed it and
  updates are dropped, which with a cumulative protocol means the user sees
  the message stall and then jump. :data:`TEAMS_MIN_UPDATE_INTERVAL_SECONDS`
  is that limit, and this sink enforces it.
* "ensure to call the next streaming API only after receiving a successful
  response from the initial API call" - so sends are serialised here, never
  fired concurrently.
* The Teams typing animation is not available while a stream is open, which
  is a second reason informative updates matter: they are the only progress
  signal the user gets.

--------------------------------------------------------------------------
WHY COALESCING IS CORRECT, AND WHY IT IS SAFE
--------------------------------------------------------------------------
A model emits tokens far faster than one per second. Blocking the read loop
to respect the throttle would stall the upstream stream. Instead, because
updates are CUMULATIVE, any intermediate update is redundant the moment a
newer one exists: the newest text already contains everything the skipped
one would have said. So :meth:`ConnectorTeamsSink.content` sends when the
rate window is open and otherwise just records the newest text as pending.
:meth:`final` always flushes.

Dropping an intermediate update is lossless here. It would be catastrophic
under a delta protocol. That asymmetry is the reason this file shouts about
the cumulative contract at the top.

--------------------------------------------------------------------------
``channelData`` VS ``entities``
--------------------------------------------------------------------------
The Learn REST documentation puts the stream fields in an ``entities`` array
entry of ``type: "streaminfo"``. Bot Framework SDK samples and several
internal notes describe the same fields on ``channelData``. Rather than bet
on one, this sink emits BOTH: the documented ``streaminfo`` entity, and a
mirrored ``channelData`` block. The extra keys are inert if unused. This is
called out in NOTES.md as doc-confirmed (entities) versus belt-and-braces
(channelData), because pretending to be certain about it would be worse than
carrying four redundant keys.
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Awaitable, Callable, Mapping, Protocol, runtime_checkable

logger = logging.getLogger(__name__)


# Microsoft: "The throttling limit is 1 request per second."
# https://learn.microsoft.com/en-us/microsoftteams/platform/bots/streaming-ux
TEAMS_MIN_UPDATE_INTERVAL_SECONDS = 1.0

# Microsoft: "Informative messages must not be more than 1 kb or 1000
# characters."
TEAMS_INFORMATIVE_MAX_CHARS = 1000

STREAM_TYPE_INFORMATIVE = "informative"
STREAM_TYPE_STREAMING = "streaming"
STREAM_TYPE_FINAL = "final"

STREAMINFO_ENTITY_TYPE = "streaminfo"


class CumulativeContractViolation(AssertionError):
    """Raised when an update would not contain everything already streamed.

    This is a programming error in the middle tier, not a user-facing
    condition, and it is checked in the sink rather than only in tests
    because the failure mode in production (a message bubble that replaces
    itself with a fragment) is silent, ugly and hard to attribute.
    """


# --------------------------------------------------------------------------
# The seam
# --------------------------------------------------------------------------


@runtime_checkable
class TeamsSink(Protocol):
    """Where the renderer sends things. Fakeable without a network.

    Deliberately three verbs and nothing else. The renderer knows about
    Teams only through this Protocol, so a test can drive the whole renderer
    with :class:`RecordingTeamsSink` and never touch the Bot Connector.
    """

    async def informative(self, text: str) -> None:
        """Show a status line ("Querying BigQuery...").

        NOT cumulative: each informative update replaces the previous one.
        Has no visible effect once content streaming has begun. Must never
        raise into the turn - a failed progress indicator is not worth
        losing an answer over.
        """
        ...

    async def content(self, cumulative_text: str) -> None:
        """Stream content. ``cumulative_text`` is EVERYTHING so far.

        The caller passes the entire response buffered to date, not the
        newest chunk. Implementations may coalesce (skip) an update, but
        must never send one that is not a superset of the last one sent.
        """
        ...

    async def final(self, text: str) -> None:
        """Send the terminating ``message`` activity and close the stream."""
        ...


# --------------------------------------------------------------------------
# Rate limiting
# --------------------------------------------------------------------------


class _RateWindow:
    """Is the throttle window open? Injectable clock so tests stay fast.

    Not a queue and not a token bucket: the only question this sink ever
    asks is "may I send right now", because a closed window means coalesce,
    not wait.
    """

    def __init__(
        self,
        min_interval: float,
        *,
        clock: Callable[[], float] | None = None,
    ) -> None:
        self._min_interval = max(0.0, min_interval)
        self._clock = clock or time.monotonic
        self._last_send: float | None = None

    @property
    def min_interval(self) -> float:
        return self._min_interval

    def is_open(self) -> bool:
        if self._min_interval <= 0 or self._last_send is None:
            return True
        return (self._clock() - self._last_send) >= self._min_interval

    def seconds_until_open(self) -> float:
        if self._min_interval <= 0 or self._last_send is None:
            return 0.0
        remaining = self._min_interval - (self._clock() - self._last_send)
        return max(0.0, remaining)

    def mark_sent(self) -> None:
        self._last_send = self._clock()


# --------------------------------------------------------------------------
# Activity construction
# --------------------------------------------------------------------------


def _streaminfo(
    *, stream_type: str, stream_id: str | None, sequence: int | None
) -> dict[str, Any]:
    entity: dict[str, Any] = {"type": STREAMINFO_ENTITY_TYPE, "streamType": stream_type}
    if stream_id:
        entity["streamId"] = stream_id
    # "Don't set streamSequence for the final message."
    if sequence is not None:
        entity["streamSequence"] = sequence
    return entity


def build_activity(
    *,
    text: str,
    stream_type: str,
    stream_id: str | None,
    sequence: int | None,
) -> dict[str, Any]:
    """Build one streaming activity as a plain dict.

    Plain dicts, no SDK types, matching ``app.errors`` - the middle tier
    stays trivially testable and does not depend on a Bot Framework version.
    """
    activity_type = "message" if stream_type == STREAM_TYPE_FINAL else "typing"
    entity = _streaminfo(stream_type=stream_type, stream_id=stream_id, sequence=sequence)
    activity: dict[str, Any] = {
        "type": activity_type,
        # The first activity of a stream is REJECTED with 400 if text is
        # missing, so text is always present, even if empty-ish upstream.
        "text": text,
        "entities": [entity],
        # Mirrored; see the module docstring on channelData vs entities.
        "channelData": {
            key: value for key, value in entity.items() if key != "type"
        },
    }
    return activity


# --------------------------------------------------------------------------
# Stream state
# --------------------------------------------------------------------------


class StreamState:
    """streamId + streamSequence bookkeeping for one Teams stream.

    Sequence numbering per the docs: "must start at 1 and increment by 1 for
    each subsequent streaming request", counting informative and content
    updates alike, and omitted entirely on the final message.
    """

    def __init__(self) -> None:
        self.stream_id: str | None = None
        self._next_sequence = 1
        self.opened = False
        self.closed = False
        self.content_started = False

    def next_sequence(self) -> int:
        sequence = self._next_sequence
        self._next_sequence += 1
        return sequence

    def adopt_stream_id(self, response: Any) -> None:
        """Capture the streamId from the response to the first activity.

        Documented: "The response includes the ``streamId``, which is
        important for executing subsequent calls." The exact key is the
        thing this reads defensively - ``streamId`` if present, otherwise
        the activity ``id``, which is what the Connector returns and what
        the SDK samples reuse.
        """
        if self.stream_id or response is None:
            return
        candidate: Any = None
        if isinstance(response, Mapping):
            candidate = response.get("streamId") or response.get("id")
        else:
            candidate = getattr(response, "stream_id", None) or getattr(response, "id", None)
        if candidate:
            self.stream_id = str(candidate)


# --------------------------------------------------------------------------
# The real sink
# --------------------------------------------------------------------------

SendActivity = Callable[[Mapping[str, Any]], Awaitable[Any]]


class ConnectorTeamsSink:
    """Sends streaming activities through an injected transport.

    The transport is a single async callable ``send(activity) -> response``.
    Keeping the HTTP out of this class is what lets the renderer tests cover
    sequence numbering and the cumulative guard with no network at all,
    while the real deployment passes a Bot Connector POST.

    Transport failures are logged and swallowed for informative and content
    updates (losing a progress tick must not lose the answer) but are
    RE-RAISED for :meth:`final`, because a lost final message means the user
    never got an answer and the caller has to know.
    """

    def __init__(
        self,
        send: SendActivity,
        *,
        min_interval: float = TEAMS_MIN_UPDATE_INTERVAL_SECONDS,
        clock: Callable[[], float] | None = None,
        log: logging.Logger | None = None,
    ) -> None:
        self._send = send
        self._state = StreamState()
        self._window = _RateWindow(min_interval, clock=clock)
        self._log = log or logger
        self._lock = asyncio.Lock()  # serialise: never two in-flight requests
        self._last_content_sent = ""
        self._pending_content: str | None = None

    # -- introspection used by the renderer and by tests ----------------

    @property
    def state(self) -> StreamState:
        return self._state

    @property
    def last_content_sent(self) -> str:
        return self._last_content_sent

    # -- TeamsSink ------------------------------------------------------

    async def informative(self, text: str) -> None:
        text = (text or "").strip()
        if not text:
            return
        if self._state.closed:
            self._log.debug("informative update after stream close; ignoring")
            return
        if self._state.content_started:
            # Documented: after the first content chunk, informative updates
            # no longer display. Sending them anyway just burns throttle
            # budget that the content updates need.
            self._log.debug("informative update after content started; skipping")
            return
        if len(text) > TEAMS_INFORMATIVE_MAX_CHARS:
            text = text[: TEAMS_INFORMATIVE_MAX_CHARS - 3] + "..."

        async with self._lock:
            if not self._window.is_open():
                # An informative update is pure status; a stale one is worth
                # nothing, so drop rather than queue.
                self._log.debug("throttled: dropping informative update %r", text)
                return
            await self._dispatch(text, STREAM_TYPE_INFORMATIVE)

    async def content(self, cumulative_text: str) -> None:
        cumulative_text = cumulative_text or ""
        if not cumulative_text:
            return
        if self._state.closed:
            self._log.debug("content update after stream close; ignoring")
            return

        self._assert_cumulative(cumulative_text)

        async with self._lock:
            if not self._window.is_open():
                # Coalesce. Safe ONLY because updates are cumulative.
                self._pending_content = cumulative_text
                self._log.debug(
                    "throttled: coalescing content update (%d chars pending)",
                    len(cumulative_text),
                )
                return
            self._pending_content = None
            await self._dispatch(cumulative_text, STREAM_TYPE_STREAMING)

    async def final(self, text: str) -> None:
        if self._state.closed:
            self._log.debug("final activity sent twice; ignoring the second")
            return
        text = text or ""
        if text:
            self._assert_cumulative(text)

        async with self._lock:
            self._pending_content = None
            # The final message is not optional and is not throttle-skippable.
            # Wait out the window rather than drop it.
            delay = self._window.seconds_until_open()
            if delay > 0:
                await asyncio.sleep(delay)
            activity = build_activity(
                text=text,
                stream_type=STREAM_TYPE_FINAL,
                stream_id=self._state.stream_id,
                sequence=None,  # docs: must NOT be set on the final message
            )
            response = await self._send(activity)
            self._state.adopt_stream_id(response)
            self._window.mark_sent()
            self._state.closed = True
            self._last_content_sent = text

    async def flush(self) -> None:
        """Send any coalesced content update. Optional; :meth:`final` also flushes."""
        pending = self._pending_content
        if pending is None or self._state.closed:
            return
        async with self._lock:
            if self._pending_content is None or self._state.closed:
                return
            delay = self._window.seconds_until_open()
            if delay > 0:
                await asyncio.sleep(delay)
            pending = self._pending_content
            self._pending_content = None
            await self._dispatch(pending, STREAM_TYPE_STREAMING)

    # -- internals ------------------------------------------------------

    def _assert_cumulative(self, text: str) -> None:
        previous = self._last_content_sent
        if previous and not text.startswith(previous):
            raise CumulativeContractViolation(
                "Teams streamed updates are cumulative: this update does not "
                "contain everything already streamed. Previously sent "
                f"{len(previous)} chars, this update starts differently. "
                "See app/streaming/README.md."
            )

    async def _dispatch(self, text: str, stream_type: str) -> None:
        activity = build_activity(
            text=text,
            stream_type=stream_type,
            stream_id=self._state.stream_id,
            sequence=self._state.next_sequence(),
        )
        try:
            response = await self._send(activity)
        except Exception:
            # A dropped progress update is a cosmetic failure. Log it and
            # keep the turn alive; the final message still carries the whole
            # answer because the protocol is cumulative.
            self._log.warning(
                "failed to send %s streaming activity; continuing", stream_type, exc_info=True
            )
            self._window.mark_sent()
            return
        self._state.adopt_stream_id(response)
        self._state.opened = True
        self._window.mark_sent()
        if stream_type == STREAM_TYPE_STREAMING:
            self._state.content_started = True
            self._last_content_sent = text


# --------------------------------------------------------------------------
# The test double
# --------------------------------------------------------------------------


class RecordingTeamsSink:
    """A :class:`TeamsSink` that records instead of sending. No network.

    Lives in production code rather than in the test file on purpose: the
    turn handler, the renderer tests and anyone debugging a stream all want
    the same fake, and three divergent copies of it is how a test double
    stops matching the thing it doubles.

    Enforces the cumulative contract on every content update, so a
    regression fails loudly in any test that uses it, not only in the tests
    that explicitly assert on it.
    """

    def __init__(self, *, enforce_cumulative: bool = True) -> None:
        self.informative_updates: list[str] = []
        self.content_updates: list[str] = []
        self.final_text: str | None = None
        self.calls: list[tuple[str, str]] = []  # (kind, text) in real order
        self.send_times: list[float] = []
        self._enforce = enforce_cumulative

    async def informative(self, text: str) -> None:
        self.informative_updates.append(text)
        self.calls.append(("informative", text))
        self.send_times.append(time.monotonic())

    async def content(self, cumulative_text: str) -> None:
        if self._enforce and self.content_updates:
            previous = self.content_updates[-1]
            if not cumulative_text.startswith(previous):
                raise CumulativeContractViolation(
                    f"update {cumulative_text!r} does not contain previous {previous!r}"
                )
        self.content_updates.append(cumulative_text)
        self.calls.append(("content", cumulative_text))
        self.send_times.append(time.monotonic())

    async def final(self, text: str) -> None:
        self.final_text = text
        self.calls.append(("final", text))
        self.send_times.append(time.monotonic())


__all__ = [
    "TeamsSink",
    "ConnectorTeamsSink",
    "RecordingTeamsSink",
    "CumulativeContractViolation",
    "StreamState",
    "build_activity",
    "TEAMS_MIN_UPDATE_INTERVAL_SECONDS",
    "TEAMS_INFORMATIVE_MAX_CHARS",
    "STREAM_TYPE_INFORMATIVE",
    "STREAM_TYPE_STREAMING",
    "STREAM_TYPE_FINAL",
]
